// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeJIptxeloAMD4IO9N_-XjqpoIVDbh67Y',
    appId: '1:994561119749:web:3693d3ec0ac6635a07ae6c',
    messagingSenderId: '994561119749',
    projectId: 'excalci-10c97',
    authDomain: 'excalci-10c97.firebaseapp.com',
    storageBucket: 'excalci-10c97.appspot.com',
    measurementId: 'G-VVKMKY4ZC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5R4ADvkANEuqD8H03J44T8Jzz5fDimeY',
    appId: '1:994561119749:android:179414da0448e0c707ae6c',
    messagingSenderId: '994561119749',
    projectId: 'excalci-10c97',
    storageBucket: 'excalci-10c97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFsdjCTm4UVAczvtyXlo_rEjdVZOkHcIM',
    appId: '1:994561119749:ios:8d6175e3972fcc8e07ae6c',
    messagingSenderId: '994561119749',
    projectId: 'excalci-10c97',
    storageBucket: 'excalci-10c97.appspot.com',
    iosBundleId: 'com.example.excalci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFsdjCTm4UVAczvtyXlo_rEjdVZOkHcIM',
    appId: '1:994561119749:ios:8d6175e3972fcc8e07ae6c',
    messagingSenderId: '994561119749',
    projectId: 'excalci-10c97',
    storageBucket: 'excalci-10c97.appspot.com',
    iosBundleId: 'com.example.excalci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeJIptxeloAMD4IO9N_-XjqpoIVDbh67Y',
    appId: '1:994561119749:web:e0539dd468734bbf07ae6c',
    messagingSenderId: '994561119749',
    projectId: 'excalci-10c97',
    authDomain: 'excalci-10c97.firebaseapp.com',
    storageBucket: 'excalci-10c97.appspot.com',
    measurementId: 'G-6SDZB4VJ4V',
  );
}
